CREATE TABLE Personas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user INTEGER NOT NULL,
    name TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    temp INTEGER NOT NULL DEFAULT 0,
    toki_pona INTEGER NOT NULL DEFAULT 0,
    last_used INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Settings (
    user INTEGER PRIMARY KEY,
    gpt INTEGER NOT NULL DEFAULT 0,
    lowercase INTEGER NOT NULL DEFAULT 1,
    punctuation INTEGER NOT NULL DEFAULT 1,
    notify_comments INTEGER NOT NULL DEFAULT 1,
    notify_replies INTEGER NOT NULL DEFAULT 1,
    dms INTEGER NOT NULL DEFAULT 0,
    persona_dms INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE SelectedPersona (
    user INTEGER PRIMARY KEY,
    persona INTEGER NOT NULL,
    FOREIGN KEY (persona) REFERENCES Personas (id)
);

CREATE TABLE AnonConnections (
    a INTEGER NOT NULL,
    b INTEGER NOT NULL
);

CREATE TABLE MeowInfo (
    unit INTEGER PRIMARY KEY CHECK (unit = 1),
    count INTEGER NOT NULL DEFAULT 0,
    time_started INTEGER
);

INSERT INTO MeowInfo DEFAULT VALUES;

CREATE TABLE Meows (
    meow TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE UserMeows (
    user INTEGER PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 0
);
